version: '3'
services:
  web:
   build:
    context: .
    dockerfile: Dockerfile.dev
   ports:
     - 8002:3000
   restart: "no"
   volumes:
     - /DOCKER-PROJECT-PROD/node_modules
     - .:/DOCKER-PROJECT-PROD  
    